version: '2'
services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
#    links:
#      - "php"
    volumes_from:
          - php:ro
    volumes:
      - ~/tmp/log/nginx:/var/log/nginx
    container_name: nginx
    networks:
      default:
        ipv4_address: 172.18.0.2

  php:
    build: ./php/7.2
    ports:
      - "9000:9000"
#    links:
#      - "mysql"
    volumes:
      - ~/PhpstormProjects:/opt/PhpstormProjects
      - ~/htdocs:/opt/htdocs
    container_name: php
    networks:
      default:
        ipv4_address: 172.18.0.3

  mysql:
    build: ./mysql
    ports:
      - "3306:3306"
    volumes:
      - ~/tmp/data/mysql:/var/lib/mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      default:
        ipv4_address: 172.18.0.4
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.18.0.0/24
        gateway: 172.18.0.1
