nginx:
    build: ./nginx
    ports:
      - "80:80"
    links:
      - "php"
    volumes:
      - ~/PhpstormProjects:/opt/PhpstormProjects
      - ~/project:/opt/htdocs
      - ~/docker/log/nginx:/var/log/nginx

php:
    build: ./php/5.6
    ports:
      - "9000:9000"
    links:
      - "mysql"
    volumes:
      - ~/PhpstormProjects:/opt/PhpstormProjects
      - ~/project:/opt/htdocs

mysql:
    build: ./mysql
    ports:
      - "3306:3306"
    volumes:
      - ~/docker/data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
